### ISSUE TITLE
ID_Meter java file

### ISSUE THREAD

**Issue by medOualla** [Dscano/QoS-Slicing#3]
Hello dears,

I want to try your app, but I got an error. Firsly I am using **onos 2.7.0**.
The first issue is that I don't know where to put the **ID_Meter.java** file. I have searched also in the onos github repositories, **I don't find a path.**
After sobstituting these files (**LinkCollectionCompiler.java; MeterManager.java, MeterServiceAdapter.java, MeterService.java 
 and VirtualNetworkMeterManager.java**). And trying to **lunch** onos, I got **this error**: 
"""
web/api/src/main/java/org/onosproject/rest/resources/MetersWebResource.java:158: error: incompatible types: MeterCellId cannot be converted to MeterId
        final Meter meter = nullIsNotFound(meterService.getMeter(did, meterCellId),
                                                                      ^
web/api/src/main/java/org/onosproject/rest/resources/MetersWebResource.java:181: error: method getMeters in interface MeterService cannot be applied to given types;
        final Iterable<Meter> meters = meterService.getMeters(did, meterScope);
                                                   ^
  required: DeviceId
  found: DeviceId,MeterScope
  reason: actual and formal argument lists differ in length
web/api/src/main/java/org/onosproject/rest/resources/MetersWebResource.java:250: error: incompatible types: MeterCellId cannot be converted to MeterId
        meterService.withdraw(meterRequest, mid);
                                            ^
web/api/src/main/java/org/onosproject/rest/resources/MetersWebResource.java:280: error: incompatible types: MeterCellId cannot be converted to MeterId
        meterService.withdraw(meterRequest, meterCellId);
                                            ^
Target //:onos-local_current-jdk failed to build
Use --verbose_failures to see the command lines of failed build steps.
INFO: Elapsed time: 105.937s, Critical Path: 100.00s
INFO: 46 processes: 5 internal, 16 linux-sandbox, 25 worker.
FAILED: Build did NOT complete successfully
FAILED: Build did NOT complete successfully
"""
Please where can I put the ID_Meter.java file. Or what to do?

Best regards,
MOHAMED.

**Comment by Dscano** [comment]
Hi,

If I remember well you have to copy ID_Meter under the folder net/meter. The error seems that appear because the method witdrown is not implemented correcly. So I think that you you have not replaced the MeterService, I clai that because in https://github.com/Dscano/QoS-Slicing/blob/main/ONOS%20File/MeterService.java#L54 the method is implemented. Pay attention you have also be sure to replace correcly the MeterManager.

**Comment by RexVaid** [comment]
Hi,

I wanted to try your app too. But getting same errors. I was using ONOS 2.7.0

After doing some debugging here is what I think maybe a problem.

In MeterService.java I found this line,
@deprecated in onos-2.5, replace MeterId with MeterCellId

Also other files may also need these changes.

**Comment by Dscano** [comment]
Hi @RexVaid,

I use MeterId because is still utilize in ONOS code, you can find here the ONOS java doc and maybe with the help of IDE you can fix this problem of type conversion

https://javadoc.io/doc/org.onosproject/onos-api/2.7.0-rc1/index.html
