### ISSUE TITLE
org.onlab.packet

### ISSUE THREAD

**Issue by gaojunyu21** [Dscano/QoS-Slicing#5]
2024-12-30T05:24:59,824 | WARN  | onos-store-app-app-activation | ApplicationManager               | 197 - org.onosproject.onos-core-net - 3.0.0.SNAPSHOT | Unable to perform operation on application org.onosproject.qosslice
org.apache.felix.resolver.reason.ReasonException: Unable to resolve root: missing requirement [root] osgi.identity; osgi.identity=qosslice-app; type=karaf.feature; version="[2.3.0.rc3,2.3.0.rc3]"; filter:="(&(osgi.identity=qosslice-app)(type=karaf.feature)(version>=2.3.0.rc3)(version<=2.3.0.rc3))" [caused by: Unable to resolve qosslice-app/2.3.0.rc3: missing requirement [qosslice-app/2.3.0.rc3] osgi.identity; osgi.identity=org.qosslice.app; type=osgi.bundle; version="[2.3.0.rc3,2.3.0.rc3]"; resolution:=mandatory [caused by: Unable to resolve org.qosslice.app/2.3.0.rc3: missing requirement [org.qosslice.app/2.3.0.rc3] osgi.wiring.package; filter:="(&(osgi.wiring.package=org.onlab.packet)(version>=2.3.0)(!(version>=3.0.0)))"]]
	at org.apache.felix.resolver.Candidates$MissingRequirementError.toException(Candidates.java:1343) ~[?:?]
	at org.apache.felix.resolver.ResolverImpl.doResolve(ResolverImpl.java:392) ~[?:?]
	at org.apache.felix.resolver.ResolverImpl.resolve(ResolverImpl.java:378) ~[?:?]
	at org.apache.felix.resolver.ResolverImpl.resolve(ResolverImpl.java:332) ~[?:?]
	at org.apache.karaf.features.internal.region.SubsystemResolver.resolve(SubsystemResolver.java:257) ~[?:?]
	at org.apache.karaf.features.internal.service.Deployer.deploy(Deployer.java:401) ~[?:?]
	at org.apache.karaf.features.internal.service.FeaturesServiceImpl.doProvision(FeaturesServiceImpl.java:1063) ~[?:?]
	at org.apache.karaf.features.internal.service.FeaturesServiceImpl.lambda$doProvisionInThread$13(FeaturesServiceImpl.java:998) ~[?:?]
	at java.util.concurrent.FutureTask.run(FutureTask.java:264) ~[?:?]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128) [?:?]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628) [?:?]
	at java.lang.Thread.run(Thread.java:829) [?:?]
Caused by: org.apache.felix.resolver.reason.ReasonException: Unable to resolve qosslice-app/2.3.0.rc3: missing requirement [qosslice-app/2.3.0.rc3] osgi.identity; osgi.identity=org.qosslice.app; type=osgi.bundle; version="[2.3.0.rc3,2.3.0.rc3]"; resolution:=mandatory [caused by: Unable to resolve org.qosslice.app/2.3.0.rc3: missing requirement [org.qosslice.app/2.3.0.rc3] osgi.wiring.package; filter:="(&(osgi.wiring.package=org.onlab.packet)(version>=2.3.0)(!(version>=3.0.0)))"]
	at org.apache.felix.resolver.Candidates$MissingRequirementError.toException(Candidates.java:1343) ~[?:?]
	... 12 more
Caused by: org.apache.felix.resolver.reason.ReasonException: Unable to resolve org.qosslice.app/2.3.0.rc3: missing requirement [org.qosslice.app/2.3.0.rc3] osgi.wiring.package; filter:="(&(osgi.wiring.package=org.onlab.packet)(version>=2.3.0)(!(version>=3.0.0)))"
	at org.apache.felix.resolver.Candidates$MissingRequirementError.toException(Candidates.java:1343) ~[?:?]
	at org.apache.felix.resolver.Candidates$MissingRequirementError.toException(Candidates.java:1343) ~[?:?]
	... 12 more

will this problem make slicing wrong?
i can activate app,but it could not work

**Comment by Dscano** [comment]
Hi @gaojunyu21,

You need to activate the VPLS app before activating the QOSSlice app. In other words, the error you are encountering is a dependency issue related to the order of app activation.

`Caused by: org.apache.felix.resolver.reason.ReasonException: Unable to resolve qosslice-app/2.3.0.rc3: missing requirement [qosslice-app/2.3.0.rc3] osgi.identity; osgi.identity=org.qosslice.app; type=osgi.bundle; version="[2.3.0.rc3,2.3.0.rc3]"; resolution:=mandatory [caused by: Unable to resolve org.qosslice.app/2.3.0.rc3: missing requirement [org.qosslice.app/2.3.0.rc3] osgi.wiring.package; filter:="(&(osgi.wiring.package=org.onlab.packet)(version>=2.3.0)(!(version>=3.0.0)))"]`

**Comment by gaojunyu21** [comment]
VPLS has worked , VPLS will activate with Qosslicing
![image](https://github.com/user-attachments/assets/88e25fe4-7741-4f93-80a7-16d308370e39)

**Comment by gaojunyu21** [comment]
I can not use the command 
"band -br -uk -b 1000 -dp 1 -nb band1 add-band     
qos-slice create SLICE-1 VPLS-1                    
qos-slice add-band SLICE-1 band1                
qos-slice add-meter SLICE-1"

**Comment by Dscano** [comment]
Can you show all the activated apps? The QOSSlicing app is not working because a required dependency app is not activated.

**Comment by gaojunyu21** [comment]
the problem is qosslice has been activated,but onos-cli tell me a warning,and I can not use the command
"band -br -uk -b 1000 -dp 1 -nb band1 add-band
qos-slice create SLICE-1 VPLS-1
qos-slice add-band SLICE-1 band1
qos-slice add-meter SLICE-1"
thank you for your reply
![image](https://github.com/user-attachments/assets/8231f720-28e0-4aab-9739-5be5b0c9ef9e)

**Comment by gaojunyu21** [comment]
I can run the topo.py ,and when i activate the following apps, mininet can connect onos
the only problem is commands above is not worked
![3809bfc182dd3c3545ac1ad3640d610](https://github.com/user-attachments/assets/d1a35f34-c44d-4b5e-805a-1a9187fcb9e3)

**Comment by Dscano** [comment]
You didn’t activate the necessary apps. Make sure to also activate Host, ARP, LLDP, and OpenFlow.

> the problem is qosslice has been activated,but onos-cli tell me a warning,and I can not use the command "band -br -uk -b 1000 -dp 1 -nb band1 add-band qos-slice create SLICE-1 VPLS-1 qos-slice add-band SLICE-1 band1 qos-slice add-meter SLICE-1" thank you for your reply ![image](https://private-user-images.githubusercontent.com/142640286/399286777-8231f720-28e0-4aab-9739-5be5b0c9ef9e.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzU1NjA0MjEsIm5iZiI6MTczNTU2MDEyMSwicGF0aCI6Ii8xNDI2NDAyODYvMzk5Mjg2Nzc3LTgyMzFmNzIwLTI4ZTAtNGFhYi05NzM5LTViZTViMGM5ZWY5ZS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMjMwJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTIzMFQxMjAyMDFaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT00NTE1YWE1N2Y0YTM5NzNhYjIxOWFmY2MxMThjYjFlMTA1ZDk2NTUwMGFiMGZmNzQ2ZjBjMTA4ZGQ0MjI2Nzg0JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.BK724WRnhYG5QRmOCT6Ms4sxDn5U7KpoP9IzZQA_HnI)

**Comment by gaojunyu21** [comment]
let me try ,thankyou

**Comment by gaojunyu21** [comment]
sorry,it doesn't work.
![image](https://github.com/user-attachments/assets/c2cc2afa-4375-4a86-b72c-80978fe7cbb6)
![image](https://github.com/user-attachments/assets/ca0c8dd0-6c6e-432d-80c6-320666d6cf60)

**Comment by gaojunyu21** [comment]
just this warning make qosslice wrong? why i can not use commands above.

**Comment by Dscano** [comment]
You still have missing dependencies among the apps. Could you check if you have an app called "Intent"

**Comment by gaojunyu21** [comment]
i don't use "onos-app localhost install! org.qosslice.app target/qosslice-app-2.3.0-rc3.oar  " to install qosslice ,because onos-app don't have argc org.qosslice.app,i can just run "onos-app localhost install!  target/qosslice-app-2.3.0-rc3.oar",and the APP ID is org.onosproject.qosslice,does it wrong?

**Comment by gaojunyu21** [comment]
I want to do something about band limit,so i can make the network stable more.
so i notice your project ,thank you for your help
i don't use "onos-app localhost install! org.qosslice.app target/qosslice-app-2.3.0-rc3.oar  " to install qosslice ,because onos-app don't have argc org.qosslice.app,i can just run "onos-app localhost install!  target/qosslice-app-2.3.0-rc3.oar",and the APP ID is org.onosproject.qosslice,does it wrong?

**Comment by gaojunyu21** [comment]
![image](https://github.com/user-attachments/assets/55f2783c-2c18-4812-b1f7-22590c842147)
which one should i activate?

**Comment by Dscano** [comment]
> ![image](https://private-user-images.githubusercontent.com/142640286/399293053-55f2783c-2c18-4812-b1f7-22590c842147.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzU1NjI4NzEsIm5iZiI6MTczNTU2MjU3MSwicGF0aCI6Ii8xNDI2NDAyODYvMzk5MjkzMDUzLTU1ZjI3ODNjLTJjMTgtNDgxMi1iMWY3LTIyNTkwYzg0MjE0Ny5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMjMwJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTIzMFQxMjQyNTFaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT04ODlkYTk1NGE1NjY4MjFlOTMwM2NkODE2NmEzMGE3Yzg0ZjlmYWE0ODE2NGIyYWE5Y2M3MDA1YTRjOGViYTcwJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.cmWYZnl8RxP1GCKfO4MXDJMeffQZYm8ImLYiT11Q7Bs) which one should i activate?

Could you please show me what you get when you type 'meter' and 'host'?

**Comment by Dscano** [comment]
Another thing you can try is moving the ONOS version to 2.3.0-rc3, publishing the artifacts to your .m2 folder, and then trying again.

**Comment by gaojunyu21** [comment]
![6ca0ee60747275e68f1bb8616b7aca3](https://github.com/user-attachments/assets/3bd1a54d-3970-4cbf-90df-74f0d7def113)
![1ad268b814282ebbee616099fb9a05c](https://github.com/user-attachments/assets/53b29c86-b61a-4e74-b559-2b3aa09c1dd4)

**Comment by gaojunyu21** [comment]
i use onos 2.7.0 and 2.2.2, i need to package qosslice again with changing onos.version in pom.xml?

**Comment by gaojunyu21** [comment]
onos version is hard to change for me .i try to package qosslice again but get some trouble

**Comment by Dscano** [comment]
try to activate also host mobility.  Can you show me also Openflows apps?

**Comment by gaojunyu21** [comment]
![image](https://github.com/user-attachments/assets/d4b2f01c-76f8-432e-99ca-355836f3d36e)

**Comment by gaojunyu21** [comment]
i need to package qosslice again with changing onos.version in pom.xml?

**Comment by Dscano** [comment]
> i use onos 2.7.0 and 2.2.2, i need to package qosslice again with changing onos.version in pom.xml?

You should rebase to ONOS 2.3 and publish the artifacts locally.

**Comment by gaojunyu21** [comment]
![1f683aae4056a2d32bb010659a8c7cf](https://github.com/user-attachments/assets/81e4ed53-3473-4657-8b1b-1646d61c75b6)
when i try to package qosslice, i get trouble with method.I don't know how to get right method,because ONOS 2.2.2 is build in docker

**Comment by gaojunyu21** [comment]
![51e9c29aabc31ac28404cc58cefdeae](https://github.com/user-attachments/assets/3e31eddc-dd2c-4b16-8d57-a25d1c8ce7f3)
.class file is here

**Comment by gaojunyu21** [comment]
I know i should replace files in "ONOS Files" in ONOS folders,but it is in docker, i can't do it

**Comment by Dscano** [comment]
The app is not going to work because you need to change the ONOS source files, as I mentioned in the `README`. I didn't realize you were using the Docker version.

Despite that, you should still be able to properly activate the QoS slice app on ONOS 2.3. You can find the Docker version here: https://hub.docker.com/r/onosproject/onos/tags?page=2.

**Comment by gaojunyu21** [comment]
ok, thank you, let me try

**Comment by gaojunyu21** [comment]
i make it.
what i do is just move the methods into .java files,then i can build qosslice successfully.
then all the commands above can be used.

**Comment by gaojunyu21** [comment]
now ,i will reboot my ONOS and try to use qosslice.if i have any question,i want help again.
thank you very much!!!
